package identity_create_trust_test

import data.identity.create_trust

test_system_admin_0 if create_trust.allow with input as {"credentials": {"user_id": "sys-admin-user", "user_domain_id": "default", "project_domain_id": "default", "domain_id": "default", "system_scope": "all", "is_admin": 1, "is_admin_project": true, "roles": ["admin", "member", "reader"], "service_roles": [], "token": {"domain": {"id": "default"}, "project": {"domain": {"id": "default"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "group": {"domain_id": "domain-a"}, "domain": {"id": "domain-a"}, "trust": {"trustor_user_id": "sys-admin-user"}, "trust.trustor_user_id": "sys-admin-user"}}
test_domain_manager_1 if create_trust.allow with input as {"credentials": {"user_id": "domain-mgr-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": ["manager", "member", "reader"], "service_roles": [], "token": {"domain": {"id": "domain-a"}, "project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "target.role.name": "member", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "group": {"domain_id": "domain-a"}, "domain": {"id": "domain-a"}, "role": {"name": "member"}, "trust": {"trustor_user_id": "domain-mgr-1"}, "trust.trustor_user_id": "domain-mgr-1"}}
test_project_admin_2 if create_trust.allow with input as {"credentials": {"project_id": "project-a", "user_id": "admin-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 1, "is_admin_project": true, "roles": ["admin", "member", "reader"], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "group": {"domain_id": "domain-a"}, "domain": {"id": "domain-a"}, "trust": {"trustor_user_id": "admin-user-1"}, "trust.trustor_user_id": "admin-user-1"}}
test_project_member_3 if create_trust.allow with input as {"credentials": {"project_id": "project-a", "user_id": "member-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": ["member"], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "credential": {"user_id": "member-user-1"}, "trust": {"trustor_user_id": "member-user-1"}, "trust.trustor_user_id": "member-user-1"}}
test_project_reader_4 if create_trust.allow with input as {"credentials": {"project_id": "project-a", "user_id": "reader-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": ["reader"], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "trust": {"trustor_user_id": "reader-user-1"}, "trust.trustor_user_id": "reader-user-1"}}
test_service_user_5 if create_trust.allow with input as {"credentials": {"project_id": "service-project", "user_id": "service-user", "user_domain_id": "default", "project_domain_id": "default", "is_admin": 0, "is_admin_project": false, "roles": ["service"], "service_roles": [], "token": {"project": {"domain": {"id": "default"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "trust": {"trustor_user_id": "service-user"}, "trust.trustor_user_id": "service-user"}}
test_deny_wrong_role_6 if not create_trust.allow with input as {"credentials": {"project_id": "project-c", "user_id": "norole-user", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": [], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "trust": {"trustor_user_id": "resource-owner"}, "trust.trustor_user_id": "resource-owner"}}
