package identity_get_limit_test

import data.identity.get_limit

test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_0 if get_limit.allow with input as {"credentials": {"roles": ["admin"]}}
test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_1 if get_limit.allow with input as {"credentials": {"is_admin": 1}}
test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_2 if get_limit.allow with input as {"credentials": {"roles": ["reader"], "system_scope": "all"}}
test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_3 if get_limit.allow with input as {"credentials": {"domain_id": "foo"}, "target": {"target": {"limit": {"domain": {"id": "foo"}}}}}
test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_4 if get_limit.allow with input as {"credentials": {"domain_id": "foo"}, "target": {"target": {"limit": {"project": {"domain_id": "foo"}}}}}
test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_5 if get_limit.allow with input as {"credentials": {"project_id": "foo"}, "target": {"target": {"limit": {"project_id": "foo"}}}}
test_admin_required_or_reader_and_creds_system_scope_eq_all_or_creds_domain_id_eq_input_target_limit_domain_id_or_creds_domain_id_eq_input_target_limit_project_domain_id_or_creds_project_id_eq_input_target_limit_project_id_and_not_input_target_limit_project_id_empty_6 if get_limit.allow with input as {"credentials": {"project_id": "foo"}, "target": {"target": {"limit": {"project_id": "foo"}}, "target.limit.project_id": "foo"}}
