package identity_list_projects_test

import data.identity.list_projects

test_system_admin_0 if list_projects.allow with input as {"credentials": {"user_id": "sys-admin-user", "user_domain_id": "default", "project_domain_id": "default", "domain_id": "default", "system_scope": "all", "is_admin": 1, "is_admin_project": true, "roles": ["admin", "member", "reader"], "service_roles": [], "token": {"domain": {"id": "default"}, "project": {"domain": {"id": "default"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "group": {"domain_id": "domain-a"}, "domain": {"id": "domain-a"}}}
test_domain_manager_1 if list_projects.allow with input as {"credentials": {"user_id": "domain-mgr-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": ["manager", "member", "reader"], "service_roles": [], "token": {"domain": {"id": "domain-a"}, "project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "target.role.name": "member", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "group": {"domain_id": "domain-a"}, "domain": {"id": "domain-a"}, "role": {"name": "member"}}}
test_project_admin_2 if list_projects.allow with input as {"credentials": {"project_id": "project-a", "user_id": "admin-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 1, "is_admin_project": true, "roles": ["admin", "member", "reader"], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "group": {"domain_id": "domain-a"}, "domain": {"id": "domain-a"}}}
test_project_member_3 if list_projects.allow with input as {"credentials": {"project_id": "project-a", "user_id": "member-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": ["member"], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}, "credential": {"user_id": "member-user-1"}}}
test_project_reader_4 if list_projects.allow with input as {"credentials": {"project_id": "project-a", "user_id": "reader-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": 0, "is_admin_project": false, "roles": ["reader"], "service_roles": [], "token": {"project": {"domain": {"id": "domain-a"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a", "target.user.domain_id": "domain-a", "target.project.domain_id": "domain-a", "target.project.id": "project-a", "target.group.domain_id": "domain-a", "user": {"domain_id": "domain-a"}, "project": {"id": "project-a", "domain_id": "domain-a"}}}
test_service_user_5 if list_projects.allow with input as {"credentials": {"project_id": "service-project", "user_id": "service-user", "user_domain_id": "default", "project_domain_id": "default", "is_admin": 0, "is_admin_project": false, "roles": ["service"], "service_roles": [], "token": {"project": {"domain": {"id": "default"}}}}, "target": {"domain_id": "domain-a", "target.domain_id": "domain-a"}}
