package create_subnetpool_tags_test

import data.create_subnetpool.tags

test_system_admin_0 if tags.allow with input as {"credentials": {"tenant_id": "sys-project-1", "project_id": "sys-project-1", "user_id": "sys-admin-user", "user_domain_id": "default", "project_domain_id": "default", "domain_id": "default", "system_scope": "all", "is_admin": true, "is_admin_project": true, "roles": ["admin", "member", "reader"], "service_roles": []}, "target": {"tenant_id": "project-a", "project_id": "project-a", "domain_id": "domain-a", "network_id": "net-1", "network:tenant_id": "project-a", "networks:shared": false}}
test_project_member_1 if tags.allow with input as {"credentials": {"tenant_id": "project-a", "project_id": "project-a", "user_id": "member-user-1", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": false, "is_admin_project": false, "roles": ["member"], "service_roles": []}, "target": {"tenant_id": "project-a", "project_id": "project-a", "domain_id": "domain-a", "network_id": "net-1", "network:tenant_id": "project-a", "networks:shared": false}}
test_deny_cross_domain_admin_2 if not tags.allow with input as {"credentials": {"tenant_id": "project-b", "project_id": "project-b", "user_id": "admin-user-b", "user_domain_id": "domain-b", "project_domain_id": "domain-b", "is_admin": true, "is_admin_project": true, "roles": ["admin", "member", "reader"], "service_roles": []}, "target": {"tenant_id": "project-a", "project_id": "project-a", "domain_id": "domain-a", "network_id": "net-1", "network:tenant_id": "project-a", "networks:shared": false}}
test_deny_cross_project_member_3 if not tags.allow with input as {"credentials": {"tenant_id": "project-b", "project_id": "project-b", "user_id": "member-user-b", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": false, "is_admin_project": false, "roles": ["member"], "service_roles": []}, "target": {"tenant_id": "project-a", "project_id": "project-a", "domain_id": "domain-a", "network_id": "net-1", "network:tenant_id": "project-a", "networks:shared": false}}
test_deny_wrong_role_4 if not tags.allow with input as {"credentials": {"tenant_id": "project-c", "project_id": "project-c", "user_id": "norole-user", "user_domain_id": "domain-a", "project_domain_id": "domain-a", "is_admin": false, "is_admin_project": false, "roles": [], "service_roles": []}, "target": {"tenant_id": "project-a", "project_id": "project-a", "domain_id": "domain-a", "network_id": "net-1", "network:tenant_id": "project-a", "networks:shared": false}}
